// This file is auto generated by build/build-entry.js'
import { VueConstructor } from 'vue/types'
import Alert from './Alert'

declare global {
  interface Window {
    Vue?: VueConstructor;
  }
}

const version = '1.0.0'

const components = [
  Alert
]

const install = Vue => {
  components.forEach(Component => {
    Vue.use(Component)
  })
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export {
  install,
  version,
  Alert
}

export default {
  install,
  version
}
