// This file is auto generated by build/build-entry.js'

import Alert from './Alert'
import Confirm from './confirm'
import IndexJs from './index.js'

const version = '1.0.0'

const components = [
  Alert,
  Confirm,
  IndexJs
]

const install = Vue => {
  components.forEach(Component => {
    Vue.use(Component)
  })
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export {
  install,
  version,
  Alert,
  Confirm,
  IndexJs
}

export default {
  install,
  version
}
